### PR TITLE
Issue 234: added onDragMove and onDragStop callbacks

### PR DESCRIPTION
**Pull request by teseo**
Is this planned to be released?

### CODE REVIEW

**Comment by mbraak** [comment]
Are you using this feature? If so, then I can apply this merge.

**Comment by teseo** [comment]
Hello,

We use jqtree quite a lot and we had another drag n drop plugin for other parts of our site. However the drag and drop functionality of jqtree seems awesome and it's way easier to integrate with these two methods in this branch than the clash it represents mixing two plugins.

I reached the issue 234 actually looking for how to do it properly. It will be very appreciated.

**Comment by mbraak** [comment]
Ok. This is now merged in the `dev` branch.

**Comment by teseo** [comment]
Many thanks for your generosity.

**Comment by mbraak** [comment]
great! closing the issue

**Pull request closed without merging**
